name: Test and Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: buntu-latest

    steps:
        - name: 'hello world'
          run: echo "Hello, world!